name: Run busted unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # leafo's github action doesn't work. So we install it manually
    - name: Set up LuaRocks
      run: |
        apt install luajit

    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacov
        luarocks install luasocket
        luarocks install bitser

    - name: Run tests
      run: |
        sudo busted --lua=luajit --coverage test/units
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: luacov.report.out
